### ISSUE TITLE
是否可以提供32位版本

### ISSUE THREAD

**Issue by xiaoyao2021** [xqXQzzz1/ClashWebBatAHK#1]
是否可以提供32位版本

**Comment by xqXQzzz1** [comment]
https://github.com/Dreamacro/clash/releases/tag/premium
下载clash-windows-386-2020.12.27.zip
然后改名成clash-win64.exe，复制到APP里覆盖原来的。
应该就能在32位系统使用了。

**Comment by xiaoyao2021** [comment]
替换了，但是显示系统不兼容。

**Comment by xqXQzzz1** [comment]
https://www.wintun.net/builds/wintun-0.10.zip
下载这个在bin\x86里面的替换掉Profile里的wintun.dll

**Comment by xqXQzzz1** [comment]
> 替换了，但是显示系统不兼容。

https://www.wintun.net/builds/wintun-0.10.zip
下载这个，用bin\x86里面的文件替换掉Profile里的wintun.dll

**Comment by xiaoyao2021** [comment]
试了，显示不兼容

**Comment by xqXQzzz1** [comment]
> 试了，显示不兼容

还有一个文件
https://curl.se/windows/dl-7.74.0_2/curl-7.74.0_2-win32-mingw.zip
bin里边的两个文件在CLASH\APP中替换

**Comment by xqXQzzz1** [comment]
> 试了，显示不兼容

新上传了一版，有空你测一下，具体看readme

**Comment by xqXQzzz1** [comment]
> 试了，显示不兼容

看一下，行不？

**Comment by xiaoyao2021** [comment]
试了一下，还是不行
